# Generated by Django 4.0.5 on 2022-07-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelnewsinfo',
            name='news_date',
            field=models.DateField(auto_now=True, verbose_name='新闻日期'),
        ),
    ]
